### ISSUE TITLE
Extract clothes broken

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/community-plugins-makeclothes#14]
Seems master is a bit broken atm. On a clean clone, when trying to extract clothes:

(sorry if I missed something about this on the forums) 

```
rna_uiItemR: property not found: MAKECLOTHES_OT_extract_clothes.extract
/home/joepal/.config/blender/2.83/scripts/addons/makeclothes/operators/extractclothes.py:52
Traceback (most recent call last):
  File "/home/joepal/.config/blender/2.83/scripts/addons/makeclothes/operators/extractclothes.py", line 60, in execute
    what = self.extract
  File "/home/joepal/system/blender-2.83.0-linux64/2.83/scripts/modules/bpy_types.py", line 713, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'MHC_OT_ExtractClothesOperator' object has no attribute 'extract'

location: <unknown location>:-1

```

**Comment by black-punkduck** [comment]
Sorry the close was done by adding a comment including the error number ... I did not know that. Can you please check. It was weird. I did a diff -r on my master (even with fresh pull) and NO difference at all. Then I cloned it again and had exactly the same problem. The props-box was empty. So I decided to figure out what is happening. Maybe a default value is not allowed for a dynamical list (here and there, sometimes, on weekends? :) ) I dunno. I hope it works for you too. Aranuvir  did some lines to beautify code and did a preselection, in a way nothing really to worry about.

**Comment by joepal1976** [comment]
I can confirm it works on my blender 2.83 now :-)

**Comment by black-punkduck** [comment]
funny. Yes the reason was: I did the last change on a 2.90 and tried it on a 2.82 yesterday. So I got the same problem. But since the values are used from a dynamic list a default=2 will only work if the json file has two members. And we can mix the members. If we want it a 100% correct, we should add a activated in the json-config. Otherwise the number 2 is simply "something" ;-)
